steps:

- name: gcr.io/cloud-builders/mvn
  args: ['-Dproject.build.sourceEncoding=UTF-8', '-Dproject.reporting.outputEncoding=UTF-8', 'clean']

- name: gcr.io/cloud-builders/mvn
  args: ['install', '-Dmaven.test.skip=true', '-Dcheckstyle.skip']

- name: gcr.io/cloud-builders/mvn
  args: ['package', '-Dmaven.test.skip=true', '-Dcheckstyle.skip']
  #Fifth step compiles and runs the packaged java file
- name: gcr.io/cloud-builders/mvn
  args: [compile,
   exec:java,
   -Dexec.mainClass=com.example.demo.PubSubToBigQuery \
   -Dexec.cleanupDaemonThreads=false \
   -Dexec.args="" \
    --project=smdata2022 \
    --jobName=myjob \
    --numWorkers=1 \
    --maxNumWorkers=3 \
    --region=us-central1 \
    --subnetwork=default \
    --network=default \
    --stagingLocation=gs://smdata2022/staging \
    --tempLocation=gs://smdata2022/temp \
    --runner=DataflowRunner \
    --project=smdata2022 \
    --datasetName=mypubsub \
    --tableName=mypubsub_table"]
  
substitutions:
  _DESTINATION_BUCKET: quickstart-dataflow-smdata2022
  _SOURCE_FILES: java/com/example/demo/

options:
  logging: CLOUD_LOGGING_ONLY
© 2022 GitHub, Inc.
Terms
Privacy
Security
