steps:

- name: gcr.io/cloud-builders/mvn
  args: ['-Dproject.build.sourceEncoding=UTF-8', '-Dproject.reporting.outputEncoding=UTF-8', 'clean']

- name: gcr.io/cloud-builders/mvn
  args: ['install', '-Dmaven.test.skip=true', '-Dcheckstyle.skip']

- name: gcr.io/cloud-builders/mvn
  args: ['package', '-Dmaven.test.skip=true', '-Dcheckstyle.skip']
  
  #Fifth step compiles and runs the packaged java file
- name: gcr.io/cloud-builders/mvn
  args: [compile,
   exec:java \
   -Dexec.mainClass=com.examples.pubsub.streaming.PubSubToGcs \
   -Dexec.cleanupDaemonThreads=false \
   -Dexec.args=" \
     --project=smdata2022 \
     --region=us-central1 \
     --inputTopic=projects/smdata2022/topics/mytopic \
     --output=gs://quickstart-dataflow-smdata2022/samples/output \
     --gcpTempLocation=gs://quickstart-dataflow-smdata2022/temp \
     --runner=DataflowRunner \
     --windowSize=2"
  
substitutions:
  _DESTINATION_BUCKET: quickstart-dataflow-smdata2022
  _SOURCE_FILES: java/com/example/demo/

options:
  logging: CLOUD_LOGGING_ONLY

