steps:
 - name: maven:3-jdk-8
   entrypoint: mvn
   args: ['package','-Dmaven.test.skip=true']

# substitutions:
#   _DESTINATION_BUCKET: quickstart-dataflow-smdata2022
#   _SOURCE_FILES: /java/com/bayer/gcde/src
options:
  logging: CLOUD_LOGGING_ONLY