steps:
 - name: maven:3-jdk-8
   entrypoint: mvn
   args: ['package','-Dmaven.test.skip=true']
 
 - name: gcr.io/cloud-builders/docker
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/hello-world', '--build-arg=JAR_FILE=target/hello-world.jar', '.']
images: ['gcr.io/$PROJECT_ID/hello-world']


options:
  logging: CLOUD_LOGGING_ONLY