steps:

- name: gcr.io/cloud-builders/mvn
  args: ['-Dproject.build.sourceEncoding=UTF-8', '-Dproject.reporting.outputEncoding=UTF-8', 'clean']

- name: gcr.io/cloud-builders/mvn
  args: ['install', '-Dmaven.test.skip=true', '-Dcheckstyle.skip']

- name: gcr.io/cloud-builders/mvn
  args: ['package', '-Dmaven.test.skip=true', '-Dcheckstyle.skip']
  
  #Fifth step compiles and runs the packaged java file
- name: gcr.io/cloud-builders/mvn
  args:
  - --project=involuted-woods-340900
  - --region=us-central1
  - --inputTopic=projects/involuted-woods-340900/topics/mytopic
  - --output=gs://quickstart-dataflow-involuted-woods-340900/samples/output
  - --gcpTempLocation=gs://quickstart-dataflow-involuted-woods-340900/samples/temp
  - --runner=DataflowRunner
  - --windowSize=2

